export const customerOrders = [
  {
    id: 'ORD-9826',
    customer: 'Cameron W.',
    email: 'cameron@example.com',
    date: 'Oct 24, 2023',
    time: '10:42 AM',
    amount: '$45.00',
    status: 'pending',
    initials: 'CW',
  },
  {
    id: 'ORD-9822',
    customer: 'Samantha W.',
    email: 'sam.w@example.com',
    date: 'Oct 24, 2023',
    time: '09:15 AM',
    amount: '$128.50',
    status: 'preparing',
    avatar:
      'https://lh3.googleusercontent.com/aida-public/AB6AXuBUmi-BKyj9Dpt3fZbcfyTWfRzktBU-6KQlQGwfgvi8XSmWt7OChJ4oGi6D8h7pj9zhpmTs3LXqVcFsk-CYBnjDV-TncGjltyRWIFGcuHls1lGPMLM_3kHsAObP1DPGzDeScEKi8zA5NoOXGhSxEYVpEgucTJEM6Fb-NvuyPblqdi2NWvl6PeE8IyS6TRO2Knp79qTk7jRLJ4BDn29JFT_gEa3kUaFbeS8ahQYDuRSKjcYo47dasH2FvyXdfztgk7BQnpQA4jM68W29',
  },
  {
    id: 'ORD-9821',
    customer: 'John Miller',
    email: 'john.m@example.com',
    date: 'Oct 23, 2023',
    time: '08:30 PM',
    amount: '$22.00',
    status: 'ready',
    initials: 'JM',
  },
  {
    id: 'ORD-9824',
    customer: 'Umar Faruk',
    email: 'john.m@example.com',
    date: 'Oct 23, 2025',
    time: '08:30 PM',
    amount: '$22.00',
    status: 'completed',
    initials: 'UF',
  },
  {
    id: 'ORD-9823',
    customer: 'YoungMill Makanakee',
    email: 'john.m@example.com',
    date: 'Oct 23, 2025',
    time: '08:30 PM',
    amount: '$22.00',
    status: 'delivered',
    initials: 'YM',
  },
  {
    id: 'ORD-9827',
    customer: 'Annie Mamma',
    email: 'john.m@example.com',
    date: 'Oct 23, 2025',
    time: '08:30 PM',
    amount: '$27.00',
    status: 'cancelled',
    initials: 'AM',
  },
];
